export const USER_JOIN = 'USER_JOIN'
export const SET_USER = 'SET_USER'
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_SIGNOUT = 'USER_SIGNOUT'
export const SET_ACTIVE_TAG = 'SET_ACTIVE_TAG'
